### ISSUE TITLE
[Bug] Power bars not respecting power bar filters

### ISSUE THREAD

**Issue by iFanatical** [Krealle/Cell_UnitFrames#109]
### Addon Version

1.3.14

### World of Warcraft Version

Retail

### Describe the bug

Power bars seem to ignore power bar filters in the Cell configuration. Upon initial login/reload, my power bars are disabled, which is what I want. Here is what that looks like:
![image](https://github.com/user-attachments/assets/6fbe47be-d8ba-4853-8b00-c0ce4dd9c333)

If I dismiss/summon my pet, here is what it turns into:
![image](https://github.com/user-attachments/assets/2487a91f-8e96-47b2-81af-8d9bdb480f4e)

Upon entering a Delve, my Player frame also randomly got power bars. After a /reload, they were gone again, as expected.

### Steps to reproduce

1. Dismiss pet
2. Summon pet
3. Profit/cry

Here is a screenshot of my power bar filters within the Cell addon:
![image](https://github.com/user-attachments/assets/29ef578a-7607-49ed-961a-d6568e75817e)

**Comment by iFanatical** [comment]
Okay, quick update -- the power bar issue appears to occur whenever I go through a load screen/fake load screen. For example, going to The Ringing Deeps, through the coreway, the issue occurs. Going through portals (i.e. Stormwind portal in Dornogal) causes the issue.

Here is a screenshot of the frames right after going through a portal:
![image](https://github.com/user-attachments/assets/47016524-4db3-445d-801c-bc636272d623)

I am unsure of the cause, but a /reload returns the frames to the "correct" state:
![image](https://github.com/user-attachments/assets/5bc1e6cb-3fde-4f77-a8db-9b1530a86193)

**Comment by iFanatical** [comment]
I don't know if this helps, but I also recorded an example of this.

https://www.youtube.com/watch?v=AV3-Am5sjVo

**Comment by Krealle** [comment]
All helpful info! Will take a look at it tomorrow.

**Comment by Krealle** [comment]
Turned out to be a race case rooted in how spec info is cached, fixed in next update 👍

**Comment by iFanatical** [comment]
Just wanted to add a note here to thank you for the addon and dedication. Hopefully it doesn't re-open the bug report...thanks so much!!!
