### ISSUE TITLE
[Bug] Player unit frame debuff widget not always displaying despite always being enabled

### ISSUE THREAD

**Issue by ahhovey** [Krealle/Cell_UnitFrames#117]
### Addon Version

1.3.16

### World of Warcraft Version

Retail

### Describe the bug

When entering a load screen or changing the Cell layout profile, the debuff display widget connected to the player frame stops displaying. The debuff widget is still enabled, but the icon and timer disappear from the frame. It can be temporarily fixed by disabling and re-enabling the debuff widget on the player frame, but it will break again if the conditions are met (like starting a key or hearthing).
This is my desired format for the Debuff widget
![Working Debuff Widget](https://github.com/user-attachments/assets/315f1b79-b5fb-4626-bfdd-e23ac986677e)
This is how it appears after changing Cell layout despite the player frame settings not changing
![After Layout Change](https://github.com/user-attachments/assets/83a23f52-d70c-4a63-882f-18112a3d12ee)
This is after the temporary fix by disabling the debuff widget and re-enabling it
![After Disabling and Reenabling Debuff Widget](https://github.com/user-attachments/assets/be0708e1-ffb5-4628-8475-44c6d2776e42)
This is how it appears after a /reload
![After UI Reload](https://github.com/user-attachments/assets/eeba2c13-782f-4df9-b781-1954c979af68)
This is again after the temporary fix
![After Disabling and Reenabling Debuff Widget 2](https://github.com/user-attachments/assets/b70aa6f1-9371-41ab-9df2-2356ad4d3ae5)

### Steps to reproduce

[Cell Profile String.txt](https://github.com/user-attachments/files/17335499/Cell.Profile.String.txt)
This is my cell profile. If you go to the debuff widget settings for the player frame they are enabled. If the debuffs aren't displaying uncheck and recheck the Enabled option. Debuffs should be displaying now. Now type /reload to reload the UI. Debuffs should no longer be displaying despite them still being enabled in the player frame debuff widget settings. The same is true for changing between Raid and Default layout.

I disabled all my other addons besides Cell and Cell - Unit Frames and the bug was still happening but these are the addons I'm using:
Auctionator
Baganator
BigWigs
BlizzMove
Cell
Cell - Unit Frames
Clique
Details!
Leatrix Plus
LittleWigs
LoggerHead
Method Raid Tools
MinimapButtonButton
Mythic Dungeon Tools
OmniCC
OmniCD
PetTracker
Plater
Postal
Premade Groups Filter
Raider.IO
RareScanner
Rarity
RCLootCouncil
Rematch
SavedInstances
Simulationcraft
Syndicator
Talent Loadout Ex
TomTom
TooltipInfo
Transcriptor
WeakAuras
World Quest Tracker
WorldBossTimers

**Comment by ahhovey** [comment]
Something different just happened while I was submitting this. I had the Cell settings open with a debuff on me and when it ticked down to 0 on the timer the icon just stayed there.
![WoWScrnShot_101024_170937](https://github.com/user-attachments/assets/3ef46dfd-5b31-483d-aa6a-fe84051f954d)
Adding the same debuff didn't refresh the timer.
![WoWScrnShot_101024_170959](https://github.com/user-attachments/assets/56112685-00a8-4541-b29b-f5f43fd22af6)
The icon still didn't go away even after the new debuff expired.
![WoWScrnShot_101024_171126](https://github.com/user-attachments/assets/f14e8dc8-424a-4914-bb9a-7f111ba63bbe)
Adding a different debuff doesn't change the display either.
![WoWScrnShot_101024_171139](https://github.com/user-attachments/assets/5ff8352d-9fdc-4dd3-8855-27787731bdc7)

**Comment by Krealle** [comment]
Okay I've found the issue, as always the culprit was myself all along 😅 
Will push a fix in next update, for now if you simply enable the dispels widget, the debuffs will work as they should till then

**Comment by ahhovey** [comment]
Thanks a bunch! Love the addon btw :^)
