### ISSUE TITLE
[Bug] Not respecting Global Scale set in Cell

### ISSUE THREAD

**Issue by FanaticNinja** [Krealle/Cell_UnitFrames#118]
### Addon Version

1.3.16

### World of Warcraft Version

Retail

### Describe the bug

Setting the scale value in Cell has no effect for the Unit Frames (player, target, targettarget, focus).

### Steps to reproduce

Try adjusting the scale.

**Comment by Krealle** [comment]
Not a bug.
You can find a snippet here that will enable scaling
https://discord.com/channels/1062050991664529498/1278371904092241920/1283123992974069881
