### ISSUE TITLE
[Bug] Tooltip on mouse over for frames doesn't work

### ISSUE THREAD

**Issue by PatriQ94** [Krealle/Cell_UnitFrames#123]
### Addon Version

v1.3.17

### World of Warcraft Version

Retail

### Describe the bug

Mouse over frames is usually used for checking out Raider IO info on mythic ratings. Currently, if you mouse over Player and Target frames using this addon the tooltip in the bottom right corner doesn't open up/show. Would be great to fix this bug.

P.S: Amazing addon!

### Steps to reproduce

Mouse over Player or Target frames, tooltip with info in bottom right doesn't show.

**Comment by Krealle** [comment]
Check your Cell settings, maybe you have tooltips disabled there. Closing since that's most likely the issue, feel free to reopen if it doesn't fix it.
![Image](https://github.com/user-attachments/assets/c688a2ce-123f-4753-92b6-eac1af604f3a)
