### ISSUE TITLE
[Feature] more than 10 buffs

### ISSUE THREAD

**Issue by zandadoum** [Krealle/Cell_UnitFrames#126]
### Describe the feature

Hello,

the only place in my UI where i show all my buffs/debuffs, is on my unit frame. 

so i'd like to ask for the slider to go higher than 10max buffs, as in raids it can easily go higher than 15

EDIT: might also be interesting to see more than 10 debuffs, specially on the target frame, to see everything on a raid boss

thank you.

### Describe the implementation

increase the amount of buffs to 20 or maybe even 40 (special events like Dragonflight Cobalt Assembly event can go really high on buffs)

**Comment by Krealle** [comment]
I've increased the cap to 20 for the next release.

If you want to increase it to 40, I've implemented support for achieving this via a snippet, you can see an example here
https://github.com/Krealle/Cell_UnitFrames/blob/master/Snippets/IncreaseMaxAuraIcons.lua
