### ISSUE TITLE
[Feature] Buff/Debuff ID on Tooltip

### ISSUE THREAD

**Issue by oesi94** [Krealle/Cell_UnitFrames#127]
### Describe the feature

Hey, is it possible to add debuff / buff ids on tooltip while hovering over it on target/player frames, or any frame at all.

### Describe the implementation

Hey, is it possible to add debuff / buff ids on tooltip while hovering over it on target/player frames, or any frame at all.

**Comment by michaelbull** [comment]
You are probably better served by [idTip](https://www.curseforge.com/wow/addons/idtip) instead of building it into this addon, as it will work universally across all tooltips.

**Comment by Krealle** [comment]
Closing since this is out of scope of this addon to manipulate tooltips.
