### ISSUE TITLE
[Feature] Boss Frames to Show Boss's Target

### ISSUE THREAD

**Issue by Addiemoon** [Krealle/Cell_UnitFrames#132]
### Describe the feature

Would like to see the target of the boss on the boss frames. Specifically this would help with things like seeing who has threat on Spiders on Ovi'nax. 

Thanks!

### Describe the implementation

Don't know if it would be something like another unit frame entirely?

**Comment by Krealle** [comment]
So looking at this again I think the desire you have for bossXtarget frames is out of scope for now, since they would be quite expensive CPU wise.

You can achieve this however using a Custom Text tag to show the target name. 
Hope that helps.
