### ISSUE TITLE
[Feature] Boss Frame Current Target Highlight

### ISSUE THREAD

**Issue by parastyle51** [Krealle/Cell_UnitFrames#142]
### Describe the feature

I would really like to see the Boss Frames have an option to highlight my current target. Currently, the boss frames have no feature to quickly distinguish my current target. The other Cell frames in my friendly group will highlight red if I left click select them as my target.

### Describe the implementation

I would like to see a checkmark box to highlight current target under the global settings configuration of the Boss frame. Adding it as a widget option would also work out I imagine but I think it's only applicable to Boss since multiple can be up during an encounter unlike Player/Target/Pet/TargetTarget/Focus.

**Comment by Krealle** [comment]
In general I need to implement highlighting - will add it to the backlog.
