### ISSUE TITLE
[Bug] Target of Target healthbar bugs out

### ISSUE THREAD

**Issue by PatriQ94** [Krealle/Cell_UnitFrames#146]
### Addon Version

v1.4.3

### World of Warcraft Version

Retail

### Describe the bug

Many times during a dungeon, happens that it shows target of target frame with like no hp. As you can see in below picture, it shows the healthbar empty, while in reality its actually full.

![image](https://github.com/user-attachments/assets/9d0d1b90-95e3-4436-b34d-1bf7a9390827)

Another example:

![image](https://github.com/user-attachments/assets/1fc6a093-9a28-4336-9c00-2e2e50326579)

### Steps to reproduce

Enable target of target, do some pew pew in dungeons.

**Comment by Krealle** [comment]
Have added an extra update check, but also added an `Always Update` toggle for the frame, that will make sure it always updates.

**Comment by PatriQ94** [comment]
Great, you're amazing!
