### ISSUE TITLE
[Feature] Detached Player Cast Bar

### ISSUE THREAD

**Issue by Arlaa** [Krealle/Cell_UnitFrames#151]
### Describe the feature

It would be nice to be able to move around the player castbar and have this completely detached/customisable (eg. longer than 500 width).

I use a weakaura for now but ideally I would replace this so it's the same as everything else in Cell. My current setup attached for reference (player castbar weakaura, target castbar is Cell).

![Setup](https://github.com/user-attachments/assets/d9e8f71f-9fec-4aa6-9e1d-05ae28ebe2c5)

Big appreciation for the development on this addon so far! 

### Describe the implementation

- Detached Castbar as an alternative to anchored

**Comment by lolswirl** [comment]
+1 to this. I'd prefer an 'anchor to center of screen' or something to similar effect, but either one works.
