### ISSUE TITLE
[Bug] Lay on Hands as NonHolyPally - Spell not learned on click cast

### ISSUE THREAD

**Issue by jfangonilo** [Krealle/Cell_UnitFrames#152]
### Addon Version

r243

### World of Warcraft Version

Retail

### Describe the bug

I get a Spell not learned error when trying to cast Lay on Hands via click casting as a Ret or Prot Paladin. I do not have the issue when Holy. I am able to cast it normally with action bar casts. Attached is a screenshot for when LoH is bound to Shift-Left Click. Other spells seem to be fine on that bind, and moving LoH to another bind yields the same "Spell not learned" error.
![image](https://github.com/user-attachments/assets/87011b02-0290-476e-af30-6015d44784fe)

### Steps to reproduce

As a Ret/Prot pally, bind LoH to any click cast. You should get a "Spell not learned" error

**Comment by Krealle** [comment]
This is a Cell bug and not a bug for this plugin, you should report it to them instead.
