### ISSUE TITLE
[Feature] Add 'Interrupted' cast bar

### ISSUE THREAD

**Issue by michaelbull** [Krealle/Cell_UnitFrames#163]
### Describe the feature

In ElvUI, there is an option to show a cast that is interrupted, with a configurable amount of 'time to hold'. indicating how long the 'interrupted' bar should stay on screen before disappearing. I would like to see this in Cell_UnitFrame's cast bars, along with some extra features (listed beneath) that ElvUI does not support.

Below is an example as it appears in ElvUI:

![image](https://github.com/user-attachments/assets/e6fe877f-78ca-4145-998a-64256f63457d)

![image](https://github.com/user-attachments/assets/bdb552be-1855-401b-8252-47249d271a4f)

### Describe the implementation

I would like to be able to:
- Choose the text label, with it defaulting to the word Interrupted
- Optionally tell you the spell name of the cast that was interrupted
- Optionally tell you the name of the unit that interrupted the cast, colored by the unit's class name, e.g. "Interrupted (Playername)" where playername is pink if the player is a paladin
- Choose the duration for how long the bar stays on screen after changing to the 'Interrupted' state, defaulting to 0.7s (the default in ElvUI)

**Comment by Krealle** [comment]
Implemented with #194.
Only thing not implemented is the source of interrupt, since this isn't information that is readily available outside of CLUE events; which I want to avoid.
