### ISSUE TITLE
[Feature] Add `abs:healabs:merge` and `abs:healabs:merge:short` health tags

### ISSUE THREAD

**Issue by michaelbull** [Krealle/Cell_UnitFrames#168]
### Describe the feature

I would like to display the combined result of my current Absorb (`[abs]`) and Heal Absorb (`[healabs]`) in a single tag: `abs:healabs:merge`, optionally shortened with `abs:healabs:merge:short`.

### Describe the implementation

- If I have no shield and no absorb, the text should be empty.
- If I have a shield of 300k health and a heal absorb of 100k, it should return `+200000` or `+200k` with the `short` modifier.
- If I have a shield of 50k health and heal absorb of 500k it should return `-450000` or `-450k` with the `short` modifier.
- Optionally, I would like to be able to change the text color, or at least have the color some form of green when a positive total and red when a negative total. Currently there is no way to change inline text of colors, I would have to use two separate texts which is not ideal.

**Comment by Krealle** [comment]
This is partially merged in now - The conditional color tags will have to wait since that would require a small refactor to implement in a performant manner. 
Please feel free to open up a new Request for that :)
