### ISSUE TITLE
[Bug] Blizzard Frame also shows

### ISSUE THREAD

**Issue by Paladin7788** [Krealle/Cell_UnitFrames#176]
### Addon Version

v 1.4.9

### World of Warcraft Version

Retail

### Describe the bug

After updating today to 1.4.9 the Target, TargetOfTarget and Boss frames, did in fact work, BUT the default Blizzard frames did also show and weren't hidden. I couldn't find if there is a new Option to hide / show selected default frames. 

 

### Steps to reproduce

Just updated to current version (1.4.9) 
Tried with only Cell and Cell unitframes enabled, still happening. 
Tried Alt F4 from game
Tried Reload, 

### BugSack

```bash
Got no Lua error for that, sorry -or maybe good?
```

**Comment by Krealle** [comment]
![image](https://github.com/user-attachments/assets/57799398-4893-48f5-8b40-32ee05066b43)

You can turn them off here

**Comment by Paladin7788** [comment]
I'm officially blind  now .. woops. Looked into the exact window 3 times and verlooked that button. Fixed everything.

One little thing I encountered, accidentally checked "Hide blizzard buffs" and they didn't reappear unchecking the option. Only a reload did help. (Maybe moveany conflicts there didn't got any errors or anything and reload was an easy fix) 
But thought you should know.

Sorry to bother, and thank you for the quick answer!

**Comment by Krealle** [comment]
Yea a reload is the only thing that will make it show up again, cant really do much about that without it getting real janky
