### ISSUE TITLE
[Bug] Frame duplicated upon updating the addon

### ISSUE THREAD

**Issue by PatriQ94** [Krealle/Cell_UnitFrames#178]
### Addon Version

v1.4.10

### World of Warcraft Version

Retail

### Describe the bug

Upon updating to latest version, the default Blizzard frames (Player) are shown again beside the addon ones, so frames are duplicated.

### Steps to reproduce

Simply updating the addon and logging into the game.

**Comment by Krealle** [comment]
![Image](https://github.com/user-attachments/assets/4f714389-e43e-4a25-9129-53600bb7c5d3)
Not a bug, the option to disable them have simply been moved here, since there was demand for such a toggle.

**Comment by PatriQ94** [comment]
> ![Image](https://private-user-images.githubusercontent.com/3404958/385244205-4f714389-e43e-4a25-9129-53600bb7c5d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDc1ODYsIm5iZiI6MTczMTQwNzI4NiwicGF0aCI6Ii8zNDA0OTU4LzM4NTI0NDIwNS00ZjcxNDM4OS1lNDNlLTRhMjUtOTEyOS01MzYwMGJiN2M1ZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTAyODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDViOTc2YTM5YTdlNmU1YmY4ODI0NzIzNDhiYjMwYzk2NTY5NTYxMDIzYmMyYjUzOWZjM2M5NDEyNDUwNmRkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.A_z_uquj_1Zmgi5hcdMtqEzIIcE7TnGp-acHB29eIIc) Not a bug, the option to disable them have simply been moved here, since there was demand for such a toggle.

But shouldn't by default be disabled then? Kinda makes no sense that by default you see duplicated frames out of the box.
