### ISSUE TITLE
[Bug] Castbar for earthen ability

### ISSUE THREAD

**Issue by Nethermoure** [Krealle/Cell_UnitFrames#192]
### Addon Version

1.14.16

### World of Warcraft Version

Retail

### Describe the bug

Hello! CUF castbar currently doesn't support Azerith Surge empower  earthen racial ability.

### Steps to reproduce

1. Log on earthen
2. Press Azerith Surge

**Comment by Krealle** [comment]
Will take a look at this tomorrow.
