### ISSUE TITLE
[Feature] Boss Frames

### ISSUE THREAD

**Issue by Krealle** [Krealle/Cell_UnitFrames#29]

**Comment by Krytos** [comment]
This one would be very much appreciated 👌

**Comment by Paladin7788** [comment]
Seconding this.  It's the only thing left for me too swap to this plug-in

**Comment by LukeKimKor** [comment]
This addon is so cool. Boss Frame is the last puzzle of this amazing addon

**Comment by Krealle** [comment]
It will most likely be coming in the next update 😄

**Comment by Rachel2373** [comment]
Really need the Boss Frame. 
This addon is awsome. Thank you for adding the Boss Frame，it would be perfect！
