### ISSUE TITLE
[Bug]  Playing Affi or Destro Warlock makes target frame appear as out of range even when u stand in meele 

### ISSUE THREAD

**Issue by YeXryu** [Krealle/Cell_UnitFrames#34]
### Addon Version

recent

### World of Warcraft Version

Retail

### Describe the bug

Hey,
Played around today and found out that while playing affli or destro warlock your target (enemy) frame appears as it would be out of range (lower alpha). Tested it on 3 warlocks and found out that the issue only occurs when you play with Drain Soul talent in Affli spec. Unfortunately I was unable to find out whats wrong with Destro. 
![WoWScrnShot_082924_203646](
![affi1](https://github.com/user-attachments/assets/37f63e62-1728-44b2-85d7-b71000ca8a55)
![affi2](https://github.com/user-attachments/assets/3dd366fe-f424-44cf-b48f-7378c62dd9f3)
![affi3](https://github.com/user-attachments/assets/ffde4a9c-573b-4679-93ad-45b70e941bc7)
![affi4](https://github.com/user-attachments/assets/b41a3399-63e6-4d8a-8bc2-1ebb8f62d1e2)
https://github.com/user-attachments/assets/bedc69c1-d82b-457e-944a-3d0be41896c5)

### Steps to reproduce

1. Play Warlock 
2. Spec into Affli and pick up Drain Soul talent
or
2. Spec into Destro 
3. Target an enemy target (e.g. dummies) 
4. Target appears as out of range
4. Even if your first target will look fine try to close it and target again to reproduce the bug

**Comment by Krealle** [comment]
So this is actually a bit interesting, the range check is made with a `Cell` function, which uses `C_Spell.IsSpellInRange` to make the range check. The API is checking `Shadow Bolt`, which most likely is a override spell, which breaks the API, resulting in OOR frames.

So technically this is a `Cell` bug and not a bug on my end, if you enable `spotlight` frames and try to target a mob, you'll get the same problem. Potentially they should be using `Drain Life` instead, but unsure if that has override too.

**Comment by Krealle** [comment]
I'll mark as closed since I'm including a temp fix in next release to resolve this issue on my end.

**Comment by YeXryu** [comment]
@Krealle Should I report it to Cell if it's not a bug related to UnitFrames?

**Comment by Krealle** [comment]
Yea prolly a good idea to let them know
