### ISSUE TITLE
[Bug] Not Working on Korean Client

### ISSUE THREAD

**Issue by WonChanChang** [Krealle/Cell_UnitFrames#49]
### Addon Version

1.2.1

### World of Warcraft Version

Retail

### Describe the bug

Not Working on Korean Client

The settings window for UnitFrames does not appear even after opening the Cell settings and navigating to the Layout section 

However, if the client's language is switched to English, the settings window appears, and the addon functions correctly. After switching back to Korean, additional settings become inaccessible, but the addon continues to work.

### Steps to reproduce

Set the client's language to Korean

### BugSack

```bash
3x Cell_UnitFrames/Locales/koKR.lua:2: attempt to index global 'CUF' (a nil value)
[string "@Cell_UnitFrames/Locales/koKR.lua"]:2: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "koKR"
(*temporary) = "attempt to index global 'CUF' (a nil value)"
```

**Comment by Krealle** [comment]
So that was a bug on my end, released a new version that fixes it :)
