### ISSUE TITLE
[Bug] Unit Frames do not go where they are placed.

### ISSUE THREAD

**Issue by easytarget13** [Krealle/Cell_UnitFrames#66]
### Addon Version

1.3.1

### World of Warcraft Version

Retail

### Describe the bug

Noticed that my player frame was not in the same place where it was saved before updating the addon. Tried to move it and it will go to a spot that is below and to the left of where I was trying to move it to. This happens to all unit frames and not just the player frame.

I am using a dual monitor set up with a smaller monitor on the right of my main monitor if that matters or affects anything.

### Steps to reproduce

Open the cell option, /cell opt
Layouts tab
Click Unit Frames in the Cell UnitFrame section. 
Click Edit mode
Tried moving the player frame to the desired position.
Unit frame move to an undesirable spot.

**Comment by Krealle** [comment]
Fixed in newest version.
