### ISSUE TITLE
[Feature] clickthrough

### ISSUE THREAD

**Issue by dejam0rt** [Krealle/Cell_UnitFrames#68]
### Describe the feature

option to clickthrough unitframe 

### Describe the implementation

having the option to clickthrough unitframe (while mouse hover still works) and make it clickable with a modifier key

**Comment by Krealle** [comment]
Hey! Sorry about taking so long to getting to this, slipped through the cracks.
I've added a snippet you can use for this:
https://github.com/Krealle/Cell_UnitFrames/blob/master/Snippets/ClickThroughFrames.lua
