### ISSUE TITLE
[Bug] Shield Bar Texture Scaling

### ISSUE THREAD

**Issue by lolswirl** [Krealle/Cell_UnitFrames#78]
### Addon Version

1.3.4

### World of Warcraft Version

Retail

### Describe the bug

shield bar texture is scaling somehow unlike cells? not really sure how else to describe
![image](https://github.com/user-attachments/assets/b546e6f6-8931-4f09-b552-c40a07f09489)

### Steps to reproduce

enable shield bar texture on unit frames

**Comment by Krealle** [comment]
Which texture are you using for the Shield Bar?

**Comment by Krealle** [comment]
So I've tried setting the texture directly and I can confirm that Cell does use the `Thick Stripes` texture, so you should be able to set that and get the same results as above.

**Comment by lolswirl** [comment]
Cell is set to 1.4 and I'm using the CUF_Scale_Snippet_UpdateAppearance callback snippet

**Comment by Krealle** [comment]
Can I get you to try running this?
`/run CUF.DB.SetColor("shieldBar", "texture", "Interface\\AddOns\\Cell\\Media\\shield");CUF:Fire("UpdateWidget", CUF.DB.GetMasterLayout(), nil, "shieldBar", "color")`

**Comment by lolswirl** [comment]
![image](https://github.com/user-attachments/assets/a634fbb1-037f-4b5f-8e0e-be7be7e95f01)
Same result

**Comment by Krealle** [comment]
does it work properly if you turn off the scaling snippet?

**Comment by lolswirl** [comment]
> What is your resolution / UI scale?

![image](https://github.com/user-attachments/assets/2b253f90-627e-4649-9ff9-c98f930f9700)
Here's this as well, if that makes a difference. Misread the ask

**Comment by lolswirl** [comment]
![image](https://github.com/user-attachments/assets/76471469-1932-4d94-ab33-c8f3f4491069)
haha yea looks pretty fine just turned the opposite way without the snippet

**Comment by Krealle** [comment]
Okay, so adding that to the list of reasons I hate scaling haha
Yea the rotation is how it looks on my end too, so thats technically intentional for now.

I'll look into figuring out a fix for it tomorrow.
