### ISSUE TITLE
[Bug] Shield Bar growth while hp moving

### ISSUE THREAD

**Issue by mainusr** [Krealle/Cell_UnitFrames#82]
### Addon Version

1.3.5

### World of Warcraft Version

Retail

### Describe the bug

Shield Bar goes outside of frame when it's attached to Health Bar and hp is moving
![Screenshot 2024-09-23 031146](https://github.com/user-attachments/assets/6e97537f-f212-4a1a-a45a-23fbfaae29d5)
screenshot showing above cell unitframes growth after hp healed, and below elvui player unitframe shield growth after hp healed.

### Steps to reproduce

Have shieldbar attached to healthbar, receive damage, use a shield, then wait for hp to heal and shield bar to move attached to healthbar

**Comment by Krealle** [comment]
Ah, missed that edgecase, can get that fixed up pretty easily 🫡
