### ISSUE TITLE
[Feature] Show aura tooltips in combat

### ISSUE THREAD

**Issue by acornellier** [Krealle/Cell_UnitFrames#87]
### Describe the feature

I'd like aura tooltips to be visible in combat. Currently they only show when out of combat.

### Describe the implementation

Perhaps a toggle to make this a configurable option.

**Comment by acornellier** [comment]
Maybe this addon is using the cell default options, which is not supposed to affect aura tooltips
![image](https://github.com/user-attachments/assets/b8804e1a-9fd6-479e-96a2-ecb195a9cfb5)

**Comment by Krealle** [comment]
Can add an option for that in next update :+1:
