### ISSUE TITLE
[Feature] Customizable Player/Target/Focus Colour options

### ISSUE THREAD

**Issue by Neyebae** [Krealle/Cell_UnitFrames#92]
### Describe the feature

Currently the frames copies over from the Cell addon and colours it that way, but it would be great to have it separated!

### Describe the implementation

An extra option under Colours perhaps would suffice.

**Comment by Krealle** [comment]
Just for scoping sake, are you after individual options for each frame, or simply separate global options for the CUF frames?

**Comment by Neyebae** [comment]
Heya

Practically just as the picture depicts, where you can add an options to show absorbs alongside shields as an overlay bar.
And then add to that a text amount as well.
This picture is from my old elvui frames.

[cid:bb497ea2-2763-4507-99b1-d984ba0d20f1]

________________________________
Fra: Vollmer ***@***.***>
Sendt: 30. september 2024 15:56
Til: Krealle/Cell_UnitFrames ***@***.***>
Cc: Neyebae ***@***.***>; Author ***@***.***>
Emne: Re: [Krealle/Cell_UnitFrames] [Feature] Customizable Player/Target/Focus Colour options (Issue #92)


Just for scoping sake, are you after individual options for each frame, or simply separate global options for the CUF frames?

**Comment by Krealle** [comment]
I don't see a picture.

**Comment by Neyebae** [comment]
Not sure why that didn't work in the first place.
But here it is!

![HealAbsorbExample](https://github.com/user-attachments/assets/96683071-80de-4dcb-a7a9-538a30692f91)

**Comment by Krealle** [comment]
Oh I think you you are referring to #95.
My question was about the frame colors :)

**Comment by Neyebae** [comment]
So sorry, it was what was on my mind at that moment :D
I personally prefer having separate colours on Raid frames to Player frames.
An example would be I use Class Colours for raid frames to easier distinct raiders for call outs.
Player frames I like them as in the picture above. 
Makes it much easier peripherally to gauge my HP without looking.
