### ISSUE TITLE
[Feature] Party frame center anchor point

### ISSUE THREAD

**Issue by Atriel5286** [Krealle/Cell_UnitFrames#97]
### Describe the feature

Option to make the frames have an anchor in the center.

### Describe the implementation

Hello,
I would like to propose adding a center frame anchor. It would help me with odd raid sizes, as while not in a "max" party, I have more of the frames to the side.

![obrázek_2024-09-30_205742341](https://github.com/user-attachments/assets/a784ff71-812d-4f46-90de-0fa2c01e76a9)

Thank you so much for reading this and wish you a good day.

**Comment by Krealle** [comment]
If you are referring to the party frames from `Cell` then you'd need to make a request at their GitHub/Discord. This is only for `Cell Unit Frames`
