### ISSUE TITLE
[Feature] Indicator for Creature Classification (Rare/Elite/Boss)

### ISSUE THREAD

**Issue by DrRockhopper** [Krealle/Cell_UnitFrames#99]
### Describe the feature

Would love to have indicators for classifications (rare, elite, boss, etc.) of creatures.

### Describe the implementation

Implementation could be either standalone widget with icon, or as tags for use in text widgets (akin to Shadowed Unit Frames.)

Included screenshots of SUF implementation.
![image](https://github.com/user-attachments/assets/f820a40e-60ae-42f9-b5df-9269a662b757)
![image](https://github.com/user-attachments/assets/9a40c873-b2f2-4d42-88b5-1927ac5850ae)

**Comment by Krealle** [comment]
This was actually on my personal todolist before I released the addon, but seems I crossed it out without actually implementing it 😆 
Will add it to the backlog 👍
